### ISSUE TITLE
Compatibilité Freebox V6 - Firmware 3.0.x

### ISSUE THREAD

**Issue by dough29** [d-matt/freebox_munin#4]
Bonjour,
une version compatible avec l'OS 3.x de Free est elle prévue ?
A priori l'API est assez fournie et fonctionne en JSON.
Merci.

**Comment by d-matt** [comment]
Bonjour,

Je n'ai plus de freebox, donc je ne ferai pas évoluer ce plugin personnellement mais toutes les contributions sont bienvenues. 
Sinon, je vous revoie vers Munin-Plugin-Freebox de vadz (https://github.com/vadz/Munin-Plugin-Freebox) qui est probablement plus en phase avec l'API actuelle.

**Comment by dough29** [comment]
Parfait, merci beaucoup pour le lien.
